[deps]
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
Integrals = "de52edbc-65ea-441a-8357-d3a637375a31"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
NBInclude = "0db19996-df87-5ea3-a455-e3a50d440464"
PrettyTables = "08abe8d2-0d0c-5749-adfa-8a2ac140af0d"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SplitApplyCombine = "03a91e81-4c3e-53e1-a0a4-9c0c8f19dd66"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
